### ISSUE TITLE
Broken on R# 2017.1 EAP8

### ISSUE THREAD

**Issue by tankbob** [MrJul/ReSharper.EnhancedTooltip#108]
Looks like Jetbrains have changed something and now resharper exceptions are fired left right and center....

Could not load type 'JetBrains.ReSharper.Psi.IValueTupleType' from assembly 'JetBrains.ReSharper.Psi, Version=108.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'.

--- EXCEPTION #1/2 [TypeLoadException]
Message = “Could not load type 'JetBrains.ReSharper.Psi.IValueTupleType' from assembly 'JetBrains.ReSharper.Psi, Version=108.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'.”
ExceptionPath = Root.InnerException
ClassName = System.TypeLoadException
Data.ReentrancyGuard.ActionName = GetEnhancedTooltips
HResult = COR_E_TYPELOAD=80131522
Source = GammaJul.ReSharper.EnhancedTooltip
TypeLoadClassName = JetBrains.ReSharper.Psi.IValueTupleType
TypeLoadAssemblyName = “JetBrains.ReSharper.Psi, Version=108.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
TypeLoadResourceID = -2146233054
StackTraceString = “
  at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendDeclaredType(IDeclaredType declaredType, QualifierDisplays expectedQualifierDisplay, Boolean appendTypeParameters, Boolean displayUnknownTypeParameters, Context context)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendType(IType type, QualifierDisplays expectedQualifierDisplay, Boolean displayUnknownTypeParameters, Context context)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendLiteralExpression(ILiteralExpression literalExpression, PresenterOptions options)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendPresentableNode(ITreeNode treeNode, PresenterOptions options)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.ColorizerPresenter.TryPresent(ITreeNode presentableNode, PresenterOptions options, PsiLanguageType languageType, HighlighterIdProvider highlighterIdProvider)
     at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.TryPresentColorized(PresentableNode presentableNode, IContextBoundSettingsStore settings)
     at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.GetIdentifierContentGroupCore(DocumentRange documentRange, IContextBoundSettingsStore settings, IHighlighter highlighter)
     at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.GetIdentifierContentGroup(DocumentRange documentRange, IContextBoundSettingsStore settings)
     at GammaJul.ReSharper.EnhancedTooltip.VisualStudio.MainQuickInfoSource.<>c__DisplayClass0_0.<AugmentQuickInfoSessionCore>g__GetEnhancedTooltips0()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Could not load type 'JetBrains.ReSharper.Psi.IValueTupleType' from assembly 'JetBrains.ReSharper.Psi, Version=108.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = <NULL>
Data.LastExtension = cs
Data.SccRevisionShell = “<there are no packages matching the criteria>”
Data.HostProductInfo = “JetBrains ReSharper Ultimate 2017.1 EAP 8 Build 108.0.20170330.123102-eap08”
Data.SubProducts.#0 = “JetBrains dotCover 2017.1 EAP 8 Build 2017.1.20170330.130028-eap08”
Data.SubProducts.#1 = “JetBrains dotTrace 2017.1 EAP 8 Build 2017.1.20170330.130653-eap08”
Data.SubProducts.#2 = “JetBrains ReSharper 2017.1 EAP 8 Build 2017.1.20170330.124318-eap08”
Data.SubProducts.#3 = “JetBrains dotMemory 2017.1 EAP 8 Build 2017.1.20170330.130038-eap08”
Data.SccRevisionEnv = “
  Platform\Core\Shell:
  	git::refs/heads/wave08-eap8::8baeabfc01d0433979e5afb0c2cb43cd062d3831
  
  
  Platform\VisualStudio:
  	git::refs/heads/wave08-eap8::0711590b2819c459da9381443a85cf1f4effa770
”
Data.VsVersion = 15.0.26228.10
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Threading.ReentrancyGuard.TryExecute(String name, Action action)
     at GammaJul.ReSharper.EnhancedTooltip.VisualStudio.MainQuickInfoSource.AugmentQuickInfoSessionCore(IQuickInfoSession session, IList`1 quickInfoContent, IDocumentMarkup documentMarkup, TooltipFormattingProvider tooltipFormattingProvider, ITrackingSpan& applicableToSpan)
     at GammaJul.ReSharper.EnhancedTooltip.VisualStudio.QuickInfoSourceBase.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 quickInfoContent, ITrackingSpan& applicableToSpan)
     at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
     at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
     at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)
     at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()
     at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.OnHoverTimer(Object sender, EventArgs e)
     at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.DispatcherOperation.InvokeImpl()
     at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
     at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Windows.Threading.DispatcherOperation.Invoke()
     at System.Windows.Threading.Dispatcher.ProcessQueue()
     at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
”

**Comment by Huntk23** [comment]
I get the same error when i put my mouse over any Method in my controllers in a ASP Core project. Though, this does not stop Enhanced Tooltip from working.

**Comment by MrJul** [comment]
Yes, some types have changed. I will fix it for ReSharper 2017.1 RTM that is due today.

**Comment by MrJul** [comment]
Fixed in v3.2.1 for R# 2017.1 RTM.
