### ISSUE TITLE
Could not load file or assembly 'JetBrains.ReSharper.Psi.Cpp

### ISSUE THREAD

**Issue by CADbloke** [MrJul/ReSharper.EnhancedTooltip#123]
vs 2017.5.6 + R# 2017.3.2

Probably related to #118  & #122. I didn't see any installation errors as per.

Logged R# as per https://resharper-support.jetbrains.com/hc/en-us/articles/115000607984-How-to-run-ReSharper-with-logging or just paste this and run this:

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe" /ReSharper.LogFile D:\resharper_log.txt /ReSharper.LogLevel Verbose
```

Every time I hovered over something the log wrote this...
```

22:19:53.419 |V| RunningAvalonWindowsList      | Found a possibly-Avalon window HWND 007B0D8E, adding to the waiting list to see for a Presentation Source.
22:19:53.429 |V| RunningAvalonWindowsList      | Possibly-Avalon window HWND 007B0D8E got WM_WINDOWPOSCHANGED and now has a Presentation Source Wisir available, listing as a window.
22:19:53.429 |V| RunningAvalonWindowsList      | << (Opening) Avalon Window HwndWrapper#007B0D8E-Wisir
22:19:54.934 |V| RunningAvalonWindowsList      | Got WM_DESTROY for Avalon window HwndWrapper#007B0D8E-Wisir, revoking.
22:19:54.934 |V| RunningAvalonWindowsList      | >> (Closing) Avalon Window HwndWrapper#007B0D8E-Wisir
22:20:07.413 |V| VsQuickInfoSourceSinceVs10    | VS14+ Preview. Content is cached. Content items 1
22:20:07.415 |V| VsIntellisenseDisableMonitor  | DISMISS VS completion session for CSharp. TextBuffer: CSharp "Vypiq" "using System; u"
22:20:07.415 |V| VsQuickInfoSourceSinceVs10    | Common. Reuse cached content. Content items 1
22:20:07.418 |E|                               | Could not load file or assembly 'JetBrains.ReSharper.Psi.Cpp, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' or one of its dependencies. The system cannot find the file specified.

--- EXCEPTION #1/2 [FileNotFoundException]
Message = “Could not load file or assembly 'JetBrains.ReSharper.Psi.Cpp, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' or one of its dependencies. The system cannot find the file specified.”
ExceptionPath = Root.InnerException
ClassName = System.IO.FileNotFoundException
Data.ReentrancyGuard.ActionName = GetEnhancedTooltips
HResult = COR_E_FILENOTFOUND=E_FILENOTFOUND=80070002
Source = GammaJul.ReSharper.EnhancedTooltip
FileNotFound_FileName = “JetBrains.ReSharper.Psi.Cpp, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
FileNotFound_FusionLog = “
  WRN: Assembly binding logging is turned OFF.
  To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
  Note: There is some performance penalty associated with assembly bind failure logging.
  To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
”
StackTraceString = “
  at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.TryPresentColorized(DeclaredElementInfo info, IContextBoundSettingsStore settings)
     at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.GetIdentifierContentGroupCore(DocumentRange documentRange, IContextBoundSettingsStore settings, IHighlighter highlighter)
     at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.GetIdentifierContentGroup(DocumentRange documentRange, IContextBoundSettingsStore settings)
     at GammaJul.ReSharper.EnhancedTooltip.VisualStudio.MainQuickInfoSource.<>c__DisplayClass0_0.<AugmentQuickInfoSessionCore>g__GetEnhancedTooltips|0()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Could not load file or assembly 'JetBrains.ReSharper.Psi.Cpp, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' or one of its dependencies. The system cannot find the file specified.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = <NULL>
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Threading.ReentrancyGuard.TryExecute(String name, Action action)
     at GammaJul.ReSharper.EnhancedTooltip.VisualStudio.MainQuickInfoSource.AugmentQuickInfoSessionCore(IQuickInfoSession session, IList`1 quickInfoContent, IDocumentMarkup documentMarkup, TooltipFormattingProvider tooltipFormattingProvider, ITrackingSpan& applicableToSpan)
     at GammaJul.ReSharper.EnhancedTooltip.VisualStudio.QuickInfoSourceBase.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 quickInfoContent, ITrackingSpan& applicableToSpan)
     at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
     at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
     at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)
     at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()
     at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.OnHoverTimer(Object sender, EventArgs e)
     at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.DispatcherOperation.InvokeImpl()
     at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
     at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Windows.Threading.DispatcherOperation.Invoke()
     at System.Windows.Threading.Dispatcher.ProcessQueue()
     at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
”

22:20:07.446 |V| VsQuickInfoSourceSinceVs10    | VS14+ Preview. Content is cached. Content items 1
22:20:07.455 |V| VsIntellisenseDisableMonitor  | DISMISS VS completion session for CSharp. TextBuffer: CSharp "Vypiq" "using System; u"
22:20:07.455 |V| VsQuickInfoSourceSinceVs10    | Common. Reuse cached content. Content items 1
22:20:07.458 |E|                               | Could not load file or assembly 'JetBrains.ReSharper.Psi.Cpp, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' or one of its dependencies. The system cannot find the file specified.

--- EXCEPTION #1/2 [FileNotFoundException]
Message = “Could not load file or
```

**Comment by CADbloke** [comment]
as per https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/118#issuecomment-364696850
