### ISSUE TITLE
Getting Errors with Resharper 2019.1 EAP7

### ISSUE THREAD

**Issue by FutureTD** [MrJul/ReSharper.EnhancedTooltip#146]
When I highlight some classes, properties, ect.. The tooltip shows fine but, when I highlight other it shows the default tooltip and the Resharper Exception browser shows this error:

Message = “Could not load type 'JetBrains.ReSharper.Psi.IExpressionTypeEx' from assembly 'JetBrains.ReSharper.Psi, Version=777.0.0.0, Culture=neutral, PublicKeyToken='.”
ExceptionPath = Root.InnerException
ClassName = System.TypeLoadException
Data.ThreadLocalDebugInfo = GetEnhancedTooltips
Data.ReentrancyGuard.ActionName = GetEnhancedTooltips
HResult = COR_E_TYPELOAD=80131522
Source = GammaJul.ReSharper.EnhancedTooltip
TypeLoadClassName = JetBrains.ReSharper.Psi.IExpressionTypeEx
TypeLoadAssemblyName = “JetBrains.ReSharper.Psi, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
TypeLoadResourceID = -2146233054
StackTraceString = “
  at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendType(IType type, QualifierDisplays expectedQualifierDisplay, Boolean displayUnknownTypeParameters, Context context)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendElementType(IDeclaredElement element, ISubstitution substitution, QualifierDisplays expectedQualifierDisplay, String before, String after, Context context)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendParameter(IParameter parameter, ISubstitution substitution, Context context)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendParameters(IDeclaredElement element, ISubstitution substitution, Boolean isTopLevel, Context context)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.CSharpColorizer.AppendDeclaredElement(IDeclaredElement element, ISubstitution substitution, PresenterOptions options, ITreeNode contextualNode)
     at GammaJul.ReSharper.EnhancedTooltip.Presentation.ColorizerPresenter.TryPresent(DeclaredElementInstance declaredElementInstance, PresenterOptions options, PsiLanguageType languageType, HighlighterIdProvider highlighterIdProvider, ITreeNode contextualNode, PresentedInfo& presentedInfo)
     at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.TryPresentColorized(DeclaredElementInfo info, IContextBoundSettingsStore settings)
     at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.GetIdentifierContentGroupCore(DocumentRange documentRange, IContextBoundSettingsStore settings, IHighlighter highlighter)
     at GammaJul.ReSharper.EnhancedTooltip.DocumentMarkup.IdentifierTooltipContentProvider.GetIdentifierContentGroup(DocumentRange documentRange, IContextBoundSettingsStore settings)
     at GammaJul.ReSharper.EnhancedTooltip.VisualStudio.MainQuickInfoSource.<>c__DisplayClass0_0.<AugmentQuickInfoSessionCore>g__GetEnhancedTooltips|0()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
”

**Comment by FutureTD** [comment]
I see you have fixed this bug, Is this version available to be used in resharper? If so how can I use it.

**Comment by MrJul** [comment]
The fix is in v.3.10‚ I've pushed it to the ReSharper plugins gallery yesterday but you have to wait a couple days for JetBrains to approve the update.
