### ISSUE TITLE
EnhancedTooltip not available in VStudio2015 with ReSharper 9.2

### ISSUE THREAD

**Issue by knittl** [MrJul/ReSharper.EnhancedTooltip#58]
I installed your extensions through the extension manager of ReSharper and it now shows up as installed. However, I don't see it in the ReSharper options dialog, nor do I see enhanced tooltips in the editor window. I only get the boring ReSharper tooltips (which are worse than the Visual Studio default tooltips)

Not sure if the problem is the extension, ReSharper, or Visual Studio. :) Is there a way to debug?

ReSharper: 9.2
Visual Studio: Professional 2015, 14.0.23107.0 D14REL

**Comment by MrJul** [comment]
That's odd! I'm using it daily with VS2015 and R# 9.2, Enhanced Tooltip v2.5.1.14. Are other ReSharper plugins working? Does uninstalling and reinstalling the extension work?

Try to run Visual Studio with the `/ReSharper.Internal` switch and see if any exception is logged.
To get logs from ReSharper use `/ReSharper.LogFile <path-to-log>`.

**Comment by knittl** [comment]
I just tested with Visual Studio 2013 and the tooltips work (I can also configure them in the ReSharper options dialog)

ReSharper log file contains one exception, which might hint at a problem (concerning TrueType fonts). Find the logfile below (sorry for the long paste, I already removed duplicate exceptions):

	09:54:59.334 |I|                               | Running under VS version 14.0.23107.0, registry root .
	09:55:02.788 |W|                               | Only TrueType fonts are supported. This is not a TrueType font.

	--- EXCEPTION #1/2 [ArgumentException]
	Message = “Only TrueType fonts are supported. This is not a TrueType font.”
	ExceptionPath = Root.InnerException
	ClassName = System.ArgumentException
	HResult = COR_E_ARGUMENT=E_INVALIDARG=80070057
	Source = System.Drawing
	StackTraceString = “
	  at System.Drawing.Font.FromLogFont(Object lf, IntPtr hdc)
		 at System.Drawing.Font.FromLogFont(Object lf)
		 at JetBrains.VsIntegration.UI.VsFontsManager.GetVSStatementCompletionFont(IVsFontAndColorStorage vsFontAndColorStorage)
	”

	--- Outer ---

	--- EXCEPTION #2/2 [LoggerException]
	Message = “Only TrueType fonts are supported. This is not a TrueType font.”
	ExceptionPath = Root
	ClassName = JetBrains.Util.LoggerException
	InnerException = “Exception #1 at Root.InnerException”
	HResult = COR_E_APPLICATION=80131600
	StackTraceString = “
	  at JetBrains.VsIntegration.UI.VsFontsManager.<UpdateFonts>b__5()
		 at JetBrains.VsIntegration.UI.VsFontsManager.<>c__DisplayClassb.<GetFont>b__a()
		 at JetBrains.Util.Logging.Logger.CatchSilent[TValue](Func`1 F)
		 at JetBrains.VsIntegration.UI.VsFontsManager.GetFont(Lifetime lifetime, Func`1 getter)
		 at JetBrains.VsIntegration.UI.VsFontsManager.UpdateFonts()
		 at JetBrains.VsIntegration.UI.VsFontsManager..ctor(Lifetime lifetime, IVsFontAndColorStorage vsFontAndColorStorage, IUIHostLocale iuiHostLocale, IThreading threading, IVsTextManager vsTextManager, VsToolsOptionsMonitor vsToolsOptionsMonitor)
		 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
		 at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
		 at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
		 at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
		 at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
		 at JetBrains.Application.Components.SingletonDescriptor.GetValue()
		 at JetBrains.Application.Components.SignatureResolution.BindArguments(List`1 argumentDescriptors, String origin)
		 at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
		 at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
		 at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
		 at JetBrains.Application.Components.SingletonDescriptor.GetValue()
		 at JetBrains.Application.Components.SignatureResolution.BindArguments(List`1 argumentDescriptors, String origin)
		 at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
		 at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
		 at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
		 at JetBrains.Application.Components.SingletonDescriptor.GetValue()
		 at JetBrains.Application.Components.DelayedInitializationStrategy.Schedule(Lifetime lifetime, IComponentDescriptor dsc)
		 at JetBrains.Application.Components.ComponentStorage.InstantiateDescriptors(IEnumerable`1 descriptors)
		 at JetBrains.Application.Components.ComponentStorage.ComposeDescriptors(ICollection`1 descriptors)
		 at JetBrains.Application.Components.ComponentStorage.Compose()
		 at JetBrains.Application.Environment.RunsProducts.RunProduct(Lifetime lifetimeProduct, IApplicationHost product, JetEnvironment environment, RunningProducts runningProducts, ILogger logger)
		 at JetBrains.Application.Environment.RunsProducts.<>c__DisplayClass2.<.ctor>b__0(Lifetime lifetimeShouldStart)
		 at JetBrains.DataFlow.SequentialLifetimes.<>c__DisplayClass6.<Next>b__5(LifetimeDefinition definition, Lifetime lifetime)
		 at JetBrains.DataFlow.Lifetimes.Define(Lifetime lifetime, String id, Action`2 FAtomic, ILogger logger)
		 at JetBrains.DataFlow.SequentialLifetimes.DefineNext(Action`2 FNext)
		 at JetBrains.DataFlow.SequentialLifetimes.Next(Action`1 FNext)
		 at JetBrains.DataFlow.IPropertyEx.<>c__DisplayClass32.<WhenTrue>b__31(PropertyChangedEventArgs`1 args)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.DataFlow.IPropertyEx.<>c__DisplayClasse`2.<FlowInto>b__d(PropertyChangedEventArgs`1 args)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.set_Value(TValue value)
		 at JetBrains.Application.ComposeVerdictWithPriority.UpdateActiveTellers[TVerdict](Lifetime lifetimeComponent, List`1 tellers, IProperty`1 propComposite)
		 at JetBrains.Application.ComposeVerdictWithPriority.<>c__DisplayClassc`1.<UpdateActiveTellers>b__a()
		 at JetBrains.DataFlow.IPropertySignalEx.<>c__DisplayClass1f`1.<Advise_NoAcknowledgement>b__1e(PropertyChangedEventArgs`1 args)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.DataFlow.IPropertyEx.<>c__DisplayClasse`2.<FlowInto>b__d(PropertyChangedEventArgs`1 args)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.Application.DataFlowEx.<>c__DisplayClass23`1.<FlowIntoGuarded_NoReplay>b__22()
		 at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
		 at JetBrains.Threading.ReentrancyGuard.ExecuteOrQueue(String name, Action action, TaskPriority priority)
		 at JetBrains.Application.DataFlowEx.<>c__DisplayClass23`1.<FlowIntoGuarded_NoReplay>b__21()
		 at JetBrains.DataFlow.ISignalEx.<>c__DisplayClass1`1.<Advise>b__0(TValue value)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.VsIntegration.Shell.VsNonZombiedProductCanBeStarted.<>c__DisplayClass4.<.ctor>b__0()
		 at JetBrains.VsIntegration.Shell.VsNonZombiedProductCanBeStarted.<>c__DisplayClass4.<.ctor>b__2(VSSPROPID vsspropid, Object o)
		 at JetBrains.VsIntegration.Interop.Shim.VsShell.Shell.IVsShell.ShellPropertyChangesSink.Microsoft.VisualStudio.Shell.Interop.IVsShellPropertyEvents.OnShellPropertyChange(Int32 propid, Object var)
	”

	09:55:04.161 |W|                               | Invalid keyboard modifier '' Error converting a string value '' to enumeration type KeyboardModifiers. Must specify valid information for parsing in the string.

	--- EXCEPTION #1/4 [ArgumentException]
	Message = “Must specify valid information for parsing in the string.”
	ExceptionPath = Root.InnerException.InnerException.InnerException
	ClassName = System.ArgumentException
	HResult = COR_E_ARGUMENT=E_INVALIDARG=80070057
	Source = mscorlib
	StackTraceString = “
	  at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
		 at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
		 at JetBrains.StringEx.ToEnum[T](String s, Boolean ignoreCase)
	”

	--- Outer ---

	--- EXCEPTION #2/4 [InvalidOperationException]
	Message = “Error converting a string value '' to enumeration type KeyboardModifiers.”
	ExceptionPath = Root.InnerException.InnerException
	ClassName = System.InvalidOperationException
	InnerException = “Exception #1 at Root.InnerException.InnerException.InnerException”
	HResult = COR_E_INVALIDOPERATION=80131509
	Source = JetBrains.Platform.Util
	StackTraceString = “
	  at JetBrains.StringEx.ToEnum[T](String s, Boolean ignoreCase)
		 at JetBrains.ActionManagement.KeyboardShortcut.ParseModifiers(String s)
	”

	--- Outer ---

	--- EXCEPTION #3/4 [KeyboardParseException]
	Message = “Invalid keyboard modifier ''”
	ExceptionPath = Root.InnerException
	ClassName = JetBrains.ActionManagement.KeyboardParseException
	InnerException = “Exception #2 at Root.InnerException.InnerException”
	HResult = COR_E_EXCEPTION=80131500
	Source = JetBrains.Platform.UI
	StackTraceString = “
	  at JetBrains.ActionManagement.KeyboardShortcut.ParseModifiers(String s)
		 at JetBrains.ActionManagement.KeyboardShortcut.Parse(String s)
		 at JetBrains.ActionManagement.KeyboardShortcut.Parse(String shortcut, KeyboardShortcut& secondShortcut)
		 at JetBrains.ActionManagement.ShortcutUtil.ParseKeyboardShortcut(String text)
		 at JetBrains.VsIntegration.Shell.ActionManagement.VsBindingsConverter.ToVsShortcut(VsLocalizer localizer, String bindingString)
		 at JetBrains.VsIntegration.Shell.ActionManagement.VsKeyBindingsCache.<>c__DisplayClass4.<>c__DisplayClass7.<CollectKeyBindings>b__3()
		 at JetBrains.Util.Logging.Logger.CatchSilent(Action action)
	”

	--- Outer ---

	--- EXCEPTION #4/4 [LoggerException]
	Message = “Invalid keyboard modifier ''”
	ExceptionPath = Root
	ClassName = JetBrains.Util.LoggerException
	InnerException = “Exception #3 at Root.InnerException”
	HResult = COR_E_APPLICATION=80131600
	StackTraceString = “
	  at JetBrains.VsIntegration.Shell.ActionManagement.VsKeyBindingsCache.<>c__DisplayClass4.<CollectKeyBindings>b__2()
		 at JetBrains.Util.Logging.Logger.CatchSilent(Action action)
		 at JetBrains.VsIntegration.Shell.ActionManagement.VsKeyBindingsCache.CollectKeyBindings()
		 at JetBrains.VsIntegration.Shell.ActionManagement.VsKeyBindingsProcessor..ctor(Lifetime lifetime, ILogger logger, IWindowsHookManager hookman, VsCommandScopeMonitor scopeMonitor, VsKeyBindingsCache keyBindingsCache, IActionDefs actionDefs)
		 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
		 at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
		 at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
		 at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
		 at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
		 at JetBrains.Application.Components.SingletonDescriptor.GetValue()
		 at JetBrains.Application.Components.DelayedInitializationStrategy.Schedule(Lifetime lifetime, IComponentDescriptor dsc)
		 at JetBrains.Application.Components.ComponentStorage.InstantiateDescriptors(IEnumerable`1 descriptors)
		 at JetBrains.Application.Components.ComponentStorage.ComposeDescriptors(ICollection`1 descriptors)
		 at JetBrains.Application.Components.ComponentStorage.Compose()
		 at JetBrains.Application.Environment.RunsProducts.RunProduct(Lifetime lifetimeProduct, IApplicationHost product, JetEnvironment environment, RunningProducts runningProducts, ILogger logger)
		 at JetBrains.Application.Environment.RunsProducts.<>c__DisplayClass2.<.ctor>b__0(Lifetime lifetimeShouldStart)
		 at JetBrains.DataFlow.SequentialLifetimes.<>c__DisplayClass6.<Next>b__5(LifetimeDefinition definition, Lifetime lifetime)
		 at JetBrains.DataFlow.Lifetimes.Define(Lifetime lifetime, String id, Action`2 FAtomic, ILogger logger)
		 at JetBrains.DataFlow.SequentialLifetimes.DefineNext(Action`2 FNext)
		 at JetBrains.DataFlow.SequentialLifetimes.Next(Action`1 FNext)
		 at JetBrains.DataFlow.IPropertyEx.<>c__DisplayClass32.<WhenTrue>b__31(PropertyChangedEventArgs`1 args)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.DataFlow.IPropertyEx.<>c__DisplayClasse`2.<FlowInto>b__d(PropertyChangedEventArgs`1 args)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.set_Value(TValue value)
		 at JetBrains.Application.ComposeVerdictWithPriority.UpdateActiveTellers[TVerdict](Lifetime lifetimeComponent, List`1 tellers, IProperty`1 propComposite)
		 at JetBrains.Application.ComposeVerdictWithPriority.<>c__DisplayClassc`1.<UpdateActiveTellers>b__a()
		 at JetBrains.DataFlow.IPropertySignalEx.<>c__DisplayClass1f`1.<Advise_NoAcknowledgement>b__1e(PropertyChangedEventArgs`1 args)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.DataFlow.IPropertyEx.<>c__DisplayClasse`2.<FlowInto>b__d(PropertyChangedEventArgs`1 args)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.Application.DataFlowEx.<>c__DisplayClass23`1.<FlowIntoGuarded_NoReplay>b__22()
		 at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
		 at JetBrains.Threading.ReentrancyGuard.ExecuteOrQueue(String name, Action action, TaskPriority priority)
		 at JetBrains.Application.DataFlowEx.<>c__DisplayClass23`1.<FlowIntoGuarded_NoReplay>b__21()
		 at JetBrains.DataFlow.ISignalEx.<>c__DisplayClass1`1.<Advise>b__0(TValue value)
		 at JetBrains.DataFlow.Signal`1.NotifySinks(TValue payload)
		 at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
		 at JetBrains.DataFlow.Property`1.FireChange(TValue old, TValue new, Object cookie)
		 at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
		 at JetBrains.VsIntegration.Shell.VsNonZombiedProductCanBeStarted.<>c__DisplayClass4.<.ctor>b__0()
		 at JetBrains.VsIntegration.Shell.VsNonZombiedProductCanBeStarted.<>c__DisplayClass4.<.ctor>b__2(VSSPROPID vsspropid, Object o)
		 at JetBrains.VsIntegration.Interop.Shim.VsShell.Shell.IVsShell.ShellPropertyChangesSink.Microsoft.VisualStudio.Shell.Interop.IVsShellPropertyEvents.OnShellPropertyChange(Int32 propid, Object var)
	”

	09:55:05.969 |I| WorkspaceHostProcessStarter   | Starting workspace host process '91e2a7a9-e01c-4f91-b702-1f53452ee4df'
	09:55:06.460 |I| HostsPool                     | IWorkspaceHostInitializationNotifier service host initialized
	09:55:08.126 |I| WorkspaceHostProcessStarter   | Workspace host '91e2a7a9-e01c-4f91-b702-1f53452ee4df' initialized in 2156 ms, pid=13192
	09:55:08.337 |I| ClientsPool                   | IAvailabilityCheckService service client initialized
	09:55:08.366 |I| ClientsPool                   | ICoverageDetailsProvider service client initialized
	09:55:08.377 |I| ClientsPool                   | ICoverageTreeStructureProvider service client initialized
	09:55:08.386 |I| ClientsPool                   | IMetadataBasedCoverageTreeConfigurator service client initialized
	09:55:08.402 |I| ClientsPool                   | IFilterableCoverageTreeConfigurator service client initialized
	09:55:08.406 |I| ClientsPool                   | ICoverageFiltersFactory service client initialized
	09:55:08.413 |I| ClientsPool                   | IRiskMetricsProvider service client initialized
	09:55:08.416 |I| ClientsPool                   | IPathMappingRootConsumer service client initialized
	09:55:08.423 |I| ClientsPool                   | IStatementRangesProvider service client initialized
	09:55:08.426 |I| ClientsPool                   | ICoverageNodeNavigationInfoProvider service client initialized
	09:55:08.430 |I| ClientsPool                   | IReverseNavigationProvider service client initialized
	09:55:08.433 |I| ClientsPool                   | IHtmlReportBuilder service client initialized
	09:55:08.437 |I| ClientsPool                   | IJsonReportBuilder service client initialized
	09:55:08.440 |I| ClientsPool                   | IUncoveredLinesReportBuilder service client initialized
	09:55:08.443 |I| ClientsPool                   | IDetailedXmlReportBuilder service client initialized
	09:55:08.446 |I| ClientsPool                   | INDependReportBuilder service client initialized
	09:55:08.449 |I| ClientsPool                   | ITeamCityReportBuilder service client initialized
	09:55:08.452 |I| ClientsPool                   | IXmlReportBuilder service client initialized
	09:55:08.460 |I| ClientsPool                   | IReverseCoverageProvider service client initialized
	09:55:08.464 |I| ClientsPool                   | ICoverageOptionsManager service client initialized
	09:55:08.480 |I| ClientsPool                   | ISnapshotLocationProvider service client initialized
	09:55:08.484 |I| ClientsPool                   | IUnitTestSessionSnapshotScopeConfigurator service client initialized
	09:55:08.489 |I| ClientsPool                   | IWorkspacePresentableNameManager service client initialized
	09:55:08.493 |I| ClientsPool                   | IWorkspaceSnapshotComplementer service client initialized
	09:55:08.500 |I| ClientsPool                   | IWorkspaceSnapshotManager service client initialized
	09:55:08.506 |I| ClientsPool                   | IWorkspaceSnapshotStateProvider service client initialized
	09:55:08.511 |I| ClientsPool                   | ISnapshotPersistenceStateManager service client initialized
	09:55:08.516 |I| ClientsPool                   | IWorkspaceSnapshotMerger service client initialized
	09:55:08.532 |I| ClientsPool                   | IWorkspaceUnitTestSessionManager service client initialized
	09:55:08.538 |I| ClientsPool                   | IWorkspaceUnitTestSessionOperationManager service client initialized
	09:55:08.563 |I| ClientsPool                   | ISolutionBasedCoverageTreeConfigurator service client initialized
	09:55:08.574 |I| ClientsPool                   | IProgressService service client initialized
	09:55:08.585 |I| ClientsPool                   | ISignalReceiverRegistrationService service client initialized
	09:55:08.650 |W| LevelDbDriver                 | Can't take mutex ReSharper.Db.-1169471454 in folder: C:\Users\user\AppData\Local\JetBrains\Transient\ReSharperPlatformVs14\v03\ShellCaches\Shell.0
	09:55:11.307 |I| AssemblyReferenceResolutionCache| Load task: Pause
	09:55:11.307 |I| VsSolutionManager10           | VSSolutionManager::VsSolutionWrapperLifetimes: Solution instance created 54724182
	09:55:14.285 |W| VsNotifications               | IVsUserNotificationsService is not registered
	09:55:14.915 |I| InstalledProductsDiscovery    | Searching for installed products in: C:\Users\user\AppData\Local\JetBrains\Installations
	09:55:14.915 |I| InstalledProductsDiscovery    |   Scanning: C:\Users\user\AppData\Local\JetBrains\Installations\dotCover03
	09:55:14.915 |I| InstalledProductsDiscovery    |     packages file found: C:\Users\user\AppData\Local\JetBrains\Installations\dotCover03\packages
	09:55:14.918 |I| InstalledProductsDiscovery    |     host recognized: dotCover03, +71 packages
	09:55:14.918 |I| InstalledProductsDiscovery    |   Scanning: C:\Users\user\AppData\Local\JetBrains\Installations\dotPeek03
	09:55:14.918 |I| InstalledProductsDiscovery    |     packages file found: C:\Users\user\AppData\Local\JetBrains\Installations\dotPeek03\packages
	09:55:14.920 |I| InstalledProductsDiscovery    |     host recognized: dotPeek03, +45 packages
	09:55:14.920 |I| InstalledProductsDiscovery    |   Scanning: C:\Users\user\AppData\Local\JetBrains\Installations\Packages
	09:55:14.920 |I| InstalledProductsDiscovery    |   Scanning: C:\Users\user\AppData\Local\JetBrains\Installations\ReSharperPlatformVs12
	09:55:14.920 |I| InstalledProductsDiscovery    |   Scanning: C:\Users\user\AppData\Local\JetBrains\Installations\ReSharperPlatformVs12_000
	09:55:14.920 |I| InstalledProductsDiscovery    |     packages file found: C:\Users\user\AppData\Local\JetBrains\Installations\ReSharperPlatformVs12_000\packages
	09:55:14.924 |I| InstalledProductsDiscovery    |     host recognized: ReSharperPlatformVs12, +73 packages
	09:55:14.924 |I| InstalledProductsDiscovery    |   Scanning: C:\Users\user\AppData\Local\JetBrains\Installations\ReSharperPlatformVs14
	09:55:14.924 |I| InstalledProductsDiscovery    |   Scanning: C:\Users\user\AppData\Local\JetBrains\Installations\ReSharperPlatformVs14_002
	09:55:14.924 |I| InstalledProductsDiscovery    |     packages file found: C:\Users\user\AppData\Local\JetBrains\Installations\ReSharperPlatformVs14_002\packages
	09:55:14.927 |I| InstalledProductsDiscovery    |     host recognized: ReSharperPlatformVs14, +73 packages
	09:55:18.834 |I| VsSolutionManager10           | VSSolutionManager::VsSolutionWrapperLifetimes: Solution load done 54724182. Lifetime.IsTerminated=False
	09:55:19.261 |I| VsDocumentOperationsHandlerWhidbey| Buffer length mismatch, resynchronizing document
	09:55:19.746 |I| PathMappingRootProvider       | Found solution root: c:\users\user\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1 for 3 ms
	09:55:20.634 |I| UnitTestSessionManager        | Loading unit-test sessions from persistent storage...
	09:55:20.635 |I| UnitTestSessionManager        | Loading unit-test sessions from persistent storage is finished.
	09:55:31.937 |W| VsOleCommandTargetHandler     | An unknown command 47f03277-5055-4922-899c-0f7f30d26bf1 : 4843. Overridden by <none>
	09:55:31.937 |W| VsOleCommandTargetHandler     | An unknown command 47f03277-5055-4922-899c-0f7f30d26bf1 : 5411. Overridden by <none>
	09:55:31.937 |W| VsOleCommandTargetHandler     | An unknown command 47f03277-5055-4922-899c-0f7f30d26bf1 : 5410. Overridden by <none>
	09:55:31.937 |W| VsOleCommandTargetHandler     | An unknown command 47f03277-5055-4922-899c-0f7f30d26bf1 : 5409. Overridden by <none>
	09:55:31.937 |W| VsOleCommandTargetHandler     | An unknown command 47f03277-5055-4922-899c-0f7f30d26bf1 : 5408. Overridden by <none>
	09:55:31.937 |W| VsOleCommandTargetHandler     | An unknown command 47f03277-5055-4922-899c-0f7f30d26bf1 : 7932. Overridden by <none>
	09:55:52.322 |I| VsSolutionManager10           | VSSolutionManager::OnBeforeCloseSolution 54724182
	09:55:52.322 |I| VsSolutionManager10           | VSSolutionManager::CloseSolutionInstance 54724182
	09:55:52.518 |I| VsSolutionManager10           | VSSolutionManager::VsSolutionWrapperLifetimes: terminated 54724182
	09:55:52.930 |I| WorkspaceHostProcessStarter   | Shutting down workspace host '91e2a7a9-e01c-4f91-b702-1f53452ee4df'
	09:55:52.934 |I| ClientsPool                   | IWorkspaceHostShutdowner service client initialized
	09:55:53.122 |I|                               | Running under VS version 14.0.23107.0, registry root .
	09:55:53.791 |I| VsPackage                     | VS Package Unloaded

**Comment by knittl** [comment]
After uninstalling and installing several times (including other extensions) it is working now. I think another extension was the culprit (it was somehow only half-installed).

Thanks for the great extension!
